### ISSUE TITLE
Method to update existing outline with new content

### ISSUE THREAD

**Issue by Leftium** [jessegrosjean/birch-outline#1]
I would  really appreciate a method that is like `createTaskPaperOutline()` that updates an already existing outline. It should probably be a method of an Outline instance. I'm not sure how this would integrate with the mutation and history parts of birch-outline...

**Use cases:**

In my project, [Todo.taskpaper](https://github.com/Leftium/todo.taskpaper), multiple views of  a single taskpaper file are sync'ed together.

1. DropBox sync. How can a birch outline be sync'ed with DropBox? Dropbox synchronizes at the file level, and birch-outline seems to synchronize only at the task/item level.
2. Freeform-text editor. Again, it is difficult/impossible to isolate which task(s) changed.
3. Another (planned) taskpaper view is a string: the taskpaper outline is exposed to a scripting environment as a string. When the string is modified by the scripting console, the taskpaper outline object is automatically updated.  And vice versa: when the outline object is modified, the string is updated with a new representation. I plan to implement this view in Todo.taskpaper's CoffeeScript REPL, but it could be a generic layer over birch-outline that makes it more intuitive and easier to use.

My work-around is to do the following every time the outline is changed outside of birch-outline:

1. Create a new outline with `createTaskPaperOutline()`
2. Attach a new change handler via` onDidEndChanges ()`.
3. Adjust any references to the old birch-outline outline object.

It does the job, but I would prefer a more elegant solution.

I am still learning how to use birch-outline, so perhaps there is a better way to use the API?

**Comment by jessegrosjean** [comment]
> DropBox sync. How can a birch outline be sync'ed with DropBox? Dropbox synchronizes at the file level, and birch-outline seems to synchronize only at the task/item level.

The "sync" would be at the file level. When you change the birch-outline model you'd need to serialize and update the dropbox file. When the dropbox file changes you would need to reload your view with a new outline model.

So it's not really sync at all, just latest change overwrites. This would work for groups of people working on the same project, but should work OK I think for individual users editing multiple views of a single document. That's generally why I think the birch-outline api is best to either "process" documents or generate "views" on them. Creating an editor is harder and introduces sync problems.

> Freeform-text editor. Again, it is difficult/impossible to isolate which task(s) changed.
> Create a new outline with createTaskPaperOutline()
> Attach a new change handler viaonDidEndChanges ().
> Adjust any references to the old birch-outline outline object.

What I do in TaskPaper.app is maintain a index tree (somewhat similar to https://codemirror.net/demo/btree.html or http://blog.atom.io/2015/06/16/optimizing-an-important-atom-primitive.html) that I use to map birch-outline items into positions in a text buffer. Then when an item changes I know where in the text buffer to make the change. And when the text buffer changes I know which item to update

The process isn't not rocket science, but getting it all working is a pretty big job. I haven't open sourced this part of my code because then it would be pretty trivial to clone TaskPaper. I need to sell that! So I've open sourced the model, but not the editor.

Not sure that I've answered your question, but generally efficiently syncing a birch-outline to a string is a big project. And unless you have that piece some things are going to be hard (like making a full editor). On the other hand for different kinds of editors (such as a calendar, that's mostly a viewer, except when you change the date on something, then I think the full serialization approach should work fine)

**Comment by Leftium** [comment]
`reloadSerialization()` turned out to be _exactly_ what  was looking for!  I think the docs could be more clear.

Another part of the documentation that could be more clear: `evaluateItemPath()` supports [TaskPaper search syntax](https://guide.taskpaper.com/reference/searches/). A very useful fact that is easy to miss~

**Comment by jessegrosjean** [comment]
Ok, I'm closing out this issue. I've updated the docs a bit for next release in those places.
